<!doctype html>


<head>



</head>
<body>
<?php require_once("test6.php"); print_r(json_encode($lat[0]));  ?>

<script>

	function showUser(str) {
	    if (str == "") {
	        document.getElementById("txtHint").innerHTML = "";
	        return;
	    } else {
	        if (window.XMLHttpRequest) {
	            // code for IE7+, Firefox, Chrome, Opera, Safari
	            xmlhttp = new XMLHttpRequest();
	        } else {
	            // code for IE6, IE5
	            xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
	        }
	        xmlhttp.onreadystatechange = function() {
	            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
	                document.getElementById("txtHint").innerHTML = xmlhttp.responseText;
	            }
	        }
	        xmlhttp.open("GET","ajaxTest2.php?q="+str,true);
	        xmlhttp.send();
	    }
	}

	function myFunction() {
	    var index;
	    var text = "<ul>";
	    var lon = <?php  echo json_encode($lon, JSON_NUMERIC_CHECK); ?>;
	    var lat = <?php  echo json_encode($lat, JSON_NUMERIC_CHECK); ?>;


	    for (index = 0; index < lon.length; index++) {
	        text += "<li>Lon: " + lon[index] + "</li><li>Lat: " + lat[index] + "</li>";

	    }
	    text += "</ul>";
	    document.getElementById("demo").innerHTML = text;
	}

</script>

<input type ="button" value ="AJAX" onclick="showUser(this.value)"/>

<div id="txtHint"></b></div>

</body>
</html>